name: Basicscmd
main: main.main
version: 1.0
commands:
  hello:
    description: say hello to anyone
    usage: /hello <player>
    permission: Basicscmd.hello
    permission-message: 你没有这样的权限